### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by Mte90** [minollisantiago/HyperPyText#2]
The readme has no instructions on how to run it so I tried `poetry run python ./run_server.py` but I got that error:

```
Traceback (most recent call last):
  File "/tmp/test/test/./run_server.py", line 3, in <module>
    from src.app import app
  File "/tmp/test/test/src/app/__init__.py", line 1, in <module>
    from .app import app
  File "/tmp/test/test/src/app/app.py", line 3, in <module>
    from app.api.routes.root import router as router_root
ModuleNotFoundError: No module named 'app'
```

**Comment by Mte90** [comment]
I had to change the app.py file inside the app folder for `from .api.routes.root import router as router_root`
